package controller

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"

	resourcev1 "k8s.io/api/resource/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/kubernetes"
	klog "k8s.io/klog/v2"
)

const (
	// CoordinatorDriverName is the identifier used in DeviceClass labels
	// and opaque configuration for the topology coordinator.
	CoordinatorDriverName = "nodepartition.dra.k8s.io"
)

// CouplingLevel indicates the topology tightness of a partition's constraints.
type CouplingLevel string

const (
	// CouplingTight means the partition's devices share a PCIe root (same switch).
	CouplingTight CouplingLevel = "tight"
	// CouplingLoose means the partition's devices share a NUMA node but not a PCIe root.
	CouplingLoose CouplingLevel = "loose"
	// CouplingNone means no cross-driver coupling constraint was applied.
	CouplingNone CouplingLevel = ""
)

// PartitionConfig is the opaque configuration embedded in DeviceClass config.
// It tells the webhook how to expand a partition claim into sub-resource requests.
type PartitionConfig struct {
	Kind         string              `json:"kind"`
	SubResources []SubResourceConfig `json:"subResources"`
	Alignments   []AlignmentConfig   `json:"alignments"`
}

// SubResourceConfig defines a sub-resource that a partition contains.
type SubResourceConfig struct {
	DeviceClass string `json:"deviceClass"`
	Count       int    `json:"count"`
	// Capacity specifies consumable capacity requests for shared devices.
	// When set, the device is shared via DRAConsumableCapacity instead of
	// exclusive allocation. The key is the capacity name (e.g., "dra.cpu/cpu"),
	// the value is the quantity string (e.g., "16").
	Capacity map[string]string `json:"capacity,omitempty"`
	// Selectors contains CEL expressions that pin this sub-resource to specific
	// topology attributes. Generated by the coordinator from topology rules so
	// each driver's devices are constrained using the driver's own attribute
	// namespace (e.g., device.attributes["gpu.amd.com"].numaNode == 0).
	Selectors []string `json:"selectors,omitempty"`
	// PartitionMode indicates the DRA partition mode for this sub-resource.
	// When set, the webhook adds a CEL selector to filter by partition type
	// (e.g., "SPX" for full GPU, "DPX" for half, "CPX" for eighth).
	PartitionMode string `json:"partitionMode,omitempty"`
}

// AlignmentConfig defines a matchAttribute constraint for the combined claim.
type AlignmentConfig struct {
	Attribute   string          `json:"attribute"`
	Requests    []string        `json:"requests"`
	Enforcement EnforcementMode `json:"enforcement"`
}

// DeviceClassManager creates and manages DeviceClass objects based on discovered partition types.
type DeviceClassManager struct {
	client     kubernetes.Interface
	driverName string
	rules      *TopologyRuleStore
}

// NewDeviceClassManager creates a new DeviceClassManager.
func NewDeviceClassManager(client kubernetes.Interface, driverName string, rules *TopologyRuleStore) *DeviceClassManager {
	if driverName == "" {
		driverName = CoordinatorDriverName
	}
	return &DeviceClassManager{
		client:     client,
		driverName: driverName,
		rules:      rules,
	}
}

// SyncDeviceClasses creates or updates DeviceClass objects for each partition type
// discovered across all nodes.
func (m *DeviceClassManager) SyncDeviceClasses(ctx context.Context, results []PartitionResult) error {
	// Collect all unique partition types and their profiles.
	// Cache the partition config to avoid computing it twice (once for key, once for DeviceClass).
	type profilePartition struct {
		profile        string
		partType       PartitionType
		representative PartitionDevice
		cachedConfig   PartitionConfig
		cachedCoupling CouplingLevel
		count          int
	}

	seen := make(map[string]*profilePartition)
	for _, result := range results {
		for _, partition := range result.Partitions {
			// Compute partition config and coupling level once.
			config, coupling := m.buildPartitionConfig(partition.Type, partition)
			key := truncateLabel(result.Profile) + "-" + string(partition.Type)
			if len(partition.NUMANodes) > 0 && partition.Type != PartitionFull {
				key += numaKeySuffix(partition.NUMANodes)
			}
			if partition.Type == PartitionPCIeRoot && len(partition.PCIeRoots) > 0 {
				key += "-" + sanitizeForName(partition.PCIeRoots[0])
			}
			if coupling != CouplingNone {
				key += "-" + string(coupling)
			}
			if pp, ok := seen[key]; ok {
				pp.count++
			} else {
				seen[key] = &profilePartition{
					profile:        result.Profile,
					partType:       partition.Type,
					representative: partition,
					cachedConfig:   config,
					cachedCoupling: coupling,
					count:          1,
				}
			}
		}
	}

	// Create/update a DeviceClass for each profile+partitionType
	for _, pp := range seen {
		dc := m.buildDeviceClassFromCache(pp.profile, pp.partType, pp.representative, pp.cachedConfig, pp.cachedCoupling, pp.count)
		if err := m.publishDeviceClass(ctx, dc); err != nil {
			return fmt.Errorf("failed to publish DeviceClass %s: %w", dc.Name, err)
		}
	}

	// Emit aggregate DeviceClasses per partition type (pcieroot, numa).
	// No NUMA/PCIe selectors — the scheduler picks placement.
	type aggregateKey struct {
		profile  string
		partType PartitionType
	}
	aggregates := make(map[aggregateKey]*profilePartition)
	for _, pp := range seen {
		if pp.partType == PartitionFull {
			continue
		}
		ak := aggregateKey{profile: pp.profile, partType: pp.partType}
		if existing, ok := aggregates[ak]; ok {
			existing.count += pp.count
		} else {
			aggConfig, aggCoupling := m.buildPartitionAggregateConfig(pp.representative)
			aggregates[ak] = &profilePartition{
				profile:        pp.profile,
				partType:       pp.partType,
				representative: pp.representative,
				cachedConfig:   aggConfig,
				cachedCoupling: aggCoupling,
				count:          pp.count,
			}
		}
	}
	for _, pp := range aggregates {
		aggRep := pp.representative
		aggRep.NUMANodes = nil
		aggRep.PCIeRoots = nil
		dc := m.buildDeviceClassFromCache(pp.profile, pp.partType, aggRep, pp.cachedConfig, CouplingNone, pp.count)
		dc.Name = string(pp.partType)
		if err := m.publishDeviceClass(ctx, dc); err != nil {
			return fmt.Errorf("failed to publish aggregate DeviceClass %s: %w", dc.Name, err)
		}
	}

	// Clean up stale DeviceClasses no longer matching any partition
	activeKeys := make(map[string]bool, len(seen))
	for key := range seen {
		activeKeys[key] = true
	}
	for ak := range aggregates {
		aggKey := truncateLabel(ak.profile) + "-" + string(ak.partType)
		activeKeys[aggKey] = true
	}
	if err := m.cleanupStaleDeviceClasses(ctx, activeKeys); err != nil {
		klog.Errorf("Failed to cleanup stale DeviceClasses: %v", err)
	}

	klog.Infof("Synced %d DeviceClasses", len(seen))
	return nil
}

// cleanupStaleDeviceClasses removes DeviceClasses that no longer match any partition.
func (m *DeviceClassManager) cleanupStaleDeviceClasses(ctx context.Context, active map[string]bool) error {
	labelSelector := fmt.Sprintf("%s/managed=true,%s/partitionType", CoordinatorDriverName, CoordinatorDriverName)
	classes, err := m.client.ResourceV1().DeviceClasses().List(ctx, metav1.ListOptions{
		LabelSelector: labelSelector,
	})
	if err != nil {
		return fmt.Errorf("failed to list DeviceClasses: %w", err)
	}

	for _, dc := range classes.Items {
		profile := dc.Labels[CoordinatorDriverName+"/profile"]
		partType := dc.Labels[CoordinatorDriverName+"/partitionType"]
		numa := dc.Labels[CoordinatorDriverName+"/numa"]
		coupling := dc.Labels[CoordinatorDriverName+"/coupling"]
		key := profile + "-" + partType
		if numa != "" {
			key += "-" + numa
		}
		if coupling != "" {
			key += "-" + coupling
		}
		if _, exists := active[key]; !exists {
			if err := m.client.ResourceV1().DeviceClasses().Delete(ctx, dc.Name, metav1.DeleteOptions{}); err != nil {
				if !errors.IsNotFound(err) {
					klog.Errorf("Failed to delete stale DeviceClass %s: %v", dc.Name, err)
				}
			} else {
				klog.Infof("Deleted stale DeviceClass %s", dc.Name)
			}
		}
	}
	return nil
}

// buildDeviceClassFromCache constructs a DeviceClass using pre-computed config and coupling.
func (m *DeviceClassManager) buildDeviceClassFromCache(profile string, partType PartitionType, representative PartitionDevice, config PartitionConfig, coupling CouplingLevel, count int) *resourcev1.DeviceClass {
	nameSuffix := ""
	if len(representative.NUMANodes) > 0 && partType != PartitionFull {
		nameSuffix = numaKeySuffix(representative.NUMANodes)
	}
	if partType == PartitionPCIeRoot && len(representative.PCIeRoots) > 0 {
		nameSuffix += "-" + sanitizeForName(representative.PCIeRoots[0])
	}

	name := m.deviceClassName(profile, partType) + nameSuffix
	if coupling != CouplingNone {
		name += "-" + string(coupling)
	}

	// Build the CEL selector
	celExpr := fmt.Sprintf(
		`device.driver == %q && device.attributes[%q].partitionType == %q`,
		m.driverName, m.driverName, string(partType),
	)
	configJSON, err := json.Marshal(config)
	if err != nil {
		klog.Errorf("Failed to marshal partition config: %v", err)
		configJSON = []byte("{}")
	}

	labels := map[string]string{
		CoordinatorDriverName + "/managed":       "true",
		CoordinatorDriverName + "/profile":       truncateLabel(profile),
		CoordinatorDriverName + "/partitionType": string(partType),
	}
	if nameSuffix != "" {
		labels[CoordinatorDriverName+"/numa"] = strings.TrimPrefix(nameSuffix, "-")
	}
	if coupling != CouplingNone {
		labels[CoordinatorDriverName+"/coupling"] = string(coupling)
	}
	if count > 1 {
		labels[CoordinatorDriverName+"/count"] = fmt.Sprintf("%d", count)
	}

	return &resourcev1.DeviceClass{
		ObjectMeta: metav1.ObjectMeta{
			Name:   name,
			Labels: labels,
		},
		Spec: resourcev1.DeviceClassSpec{
			Selectors: []resourcev1.DeviceSelector{
				{
					CEL: &resourcev1.CELDeviceSelector{
						Expression: celExpr,
					},
				},
			},
			Config: []resourcev1.DeviceClassConfiguration{
				{
					DeviceConfiguration: resourcev1.DeviceConfiguration{
						Opaque: &resourcev1.OpaqueDeviceConfiguration{
							Driver:     m.driverName,
							Parameters: runtime.RawExtension{Raw: configJSON},
						},
					},
				},
			},
		},
	}
}

// buildPartitionConfig builds the opaque PartitionConfig from the representative partition.
func (m *DeviceClassManager) buildPartitionConfig(_ PartitionType, representative PartitionDevice) (PartitionConfig, CouplingLevel) {
	config := PartitionConfig{
		Kind: "PartitionConfig",
	}

	// Sub-resources: one entry per driver with its device count, optional capacity,
	// per-driver CEL selectors for NUMA pinning, and partition mode if applicable.
	for driver, count := range representative.DeviceCounts {
		sr := SubResourceConfig{
			DeviceClass: m.rules.GetDeviceClassForDriver(driver),
			Count:       count,
		}
		if representative.DeviceCapacity != nil {
			if cap, ok := representative.DeviceCapacity[driver]; ok {
				sr.Capacity = cap
			}
		}

		// Detect partition mode from representative devices' extended attributes.
		// Drivers advertise mode via attributes like "gpu.amd.com/partitionMode".
		for _, dev := range representative.Devices {
			if baseDriverName(dev.DriverName) != driver {
				continue
			}
			if modeAttr, mode := detectPartitionModeAttr(dev); mode != "" {
				sr.PartitionMode = mode
				parts := strings.SplitN(modeAttr, "/", 2)
				if len(parts) == 2 {
					sr.Selectors = append(sr.Selectors,
						fmt.Sprintf(`device.attributes[%q].%s == %q`, parts[0], parts[1], mode))
				} else {
					// Unqualified attribute — qualify with driver name.
					sr.Selectors = append(sr.Selectors,
						fmt.Sprintf(`device.attributes[%q].%s == %q`, driver, modeAttr, mode))
				}
				break
			}
		}

		// Generate per-driver NUMA CEL selector from topology rules.
		// Each driver publishes NUMA under its own attribute namespace
		// (e.g., gpu.amd.com/numaNode, dra.cpu/numaNodeID). The topology
		// rules tell us which attribute name each driver uses.
		if len(representative.NUMANodes) > 0 {
			if attr, ok := m.rules.GetNUMAAttributeForDriver(driver); ok {
				// Qualify unqualified attributes with the driver name.
				// E.g., "numaNode" for driver "gpu.amd.com" → "gpu.amd.com/numaNode"
				// so the CEL expression uses device.attributes["gpu.amd.com"].numaNode
				if !strings.Contains(attr, "/") {
					attr = driver + "/" + attr
				}
				cel := BuildNUMACELSelector(attr, representative.NUMANodes)
				if cel != "" {
					sr.Selectors = append(sr.Selectors, cel)
				}
			} else {
				// Fallback: driver publishes the standard resource.kubernetes.io/numaNode directly
				cel := BuildNUMACELSelector(AttrNUMANode, representative.NUMANodes)
				if cel != "" {
					sr.Selectors = append(sr.Selectors, cel)
				}
			}
		}

		config.SubResources = append(config.SubResources, sr)
	}

	// No cross-driver matchAttribute for NUMA — each sub-resource has its own
	// per-driver CEL selector derived from topology rules. This eliminates the
	// requirement for all drivers to publish NUMA under a common attribute name.

	// Match constraint alignments from topology rules with distance-based fallback.
	// For rules with FallbackAttribute, check if the primary constraint is satisfiable
	// for this partition's devices. If yes, emit it (tight coupling). If not, skip it
	// and rely on the per-driver NUMA CEL selectors already generated above (loose coupling).
	coupling := CouplingNone
	matchRules := m.rules.GetMatchConstraintRules()
	for _, rule := range matchRules {
		if rule.Driver != "" {
			if _, ok := representative.DeviceCounts[rule.Driver]; !ok {
				continue
			}
		}

		enforcement := rule.Enforcement
		if enforcement == "" {
			enforcement = EnforcementRequired
		}

		// Build request names for this constraint: only include drivers whose
		// devices actually publish the attribute. CPU and memory don't publish
		// pcieRoot, so including them in a pcieRoot matchAttribute makes the
		// constraint unsatisfiable.
		var constraintRequests []string
		if len(representative.Devices) > 0 {
			driversWithAttribute := make(map[string]bool)
			for _, dev := range representative.Devices {
				val := deviceAttributeValueString(dev, rule.Attribute)
				if val != "" {
					driversWithAttribute[baseDriverName(dev.DriverName)] = true
				}
			}
			for driver := range representative.DeviceCounts {
				if driversWithAttribute[baseDriverName(driver)] {
					constraintRequests = append(constraintRequests, driver)
				}
			}
			if len(constraintRequests) == 0 {
				continue
			}
		} else {
			// No device data available — include all drivers
			for driver := range representative.DeviceCounts {
				constraintRequests = append(constraintRequests, driver)
			}
		}

		if rule.FallbackAttribute != "" {
			// Distance-based fallback: check if primary constraint is satisfiable
			// for this specific partition's devices.
			if isPartitionConstraintSatisfiable(representative.Devices, rule.Attribute, representative.DeviceCounts) {
				// Primary (tight) constraint works for this partition
				config.Alignments = append(config.Alignments, AlignmentConfig{
					Attribute:   rule.Attribute,
					Requests:    constraintRequests,
					Enforcement: enforcement,
				})
				// Upgrade coupling to tight (never downgrade from tight)
				coupling = CouplingTight
				klog.V(2).Infof("Partition %s: primary constraint %s satisfiable (tight coupling)",
					representative.Name, rule.Attribute)
			} else {
				// Primary unsatisfiable — fall back to looser alignment.
				// Per-driver NUMA CEL selectors are already in place, so we
				// just don't add the primary matchAttribute constraint.
				if coupling != CouplingTight {
					coupling = CouplingLoose
				}
				klog.V(2).Infof("Partition %s: primary constraint %s unsatisfiable, falling back to %s (loose coupling)",
					representative.Name, rule.Attribute, rule.FallbackAttribute)
			}
		} else {
			// No fallback: emit as before
			config.Alignments = append(config.Alignments, AlignmentConfig{
				Attribute:   rule.Attribute,
				Requests:    constraintRequests,
				Enforcement: enforcement,
			})
		}
	}

	return config, coupling
}

// buildPartitionAggregateConfig builds a PartitionConfig without NUMA/PCIe
// selectors for aggregate DeviceClasses. Keeps alignment constraints and
// device counts but lets the scheduler choose placement freely.
func (m *DeviceClassManager) buildPartitionAggregateConfig(representative PartitionDevice) (PartitionConfig, CouplingLevel) {
	config := PartitionConfig{
		Kind: "PartitionConfig",
	}

	for driver, count := range representative.DeviceCounts {
		sr := SubResourceConfig{
			DeviceClass: m.rules.GetDeviceClassForDriver(driver),
			Count:       count,
		}
		if representative.DeviceCapacity != nil {
			if cap, ok := representative.DeviceCapacity[driver]; ok {
				sr.Capacity = cap
			}
		}
		config.SubResources = append(config.SubResources, sr)
	}

	coupling := CouplingNone
	matchRules := m.rules.GetMatchConstraintRules()
	for _, rule := range matchRules {
		if rule.Driver != "" {
			if _, ok := representative.DeviceCounts[rule.Driver]; !ok {
				continue
			}
		}

		var constraintRequests []string
		if len(representative.Devices) > 0 {
			driversWithAttribute := make(map[string]bool)
			for _, dev := range representative.Devices {
				val := deviceAttributeValueString(dev, rule.Attribute)
				if val != "" {
					driversWithAttribute[baseDriverName(dev.DriverName)] = true
				}
			}
			for driver := range representative.DeviceCounts {
				if driversWithAttribute[baseDriverName(driver)] {
					constraintRequests = append(constraintRequests, driver)
				}
			}
			if len(constraintRequests) == 0 {
				continue
			}
		}

		if len(constraintRequests) < 2 {
			continue
		}

		enforcement := rule.Enforcement
		if enforcement == "" {
			enforcement = EnforcementRequired
		}

		config.Alignments = append(config.Alignments, AlignmentConfig{
			Attribute:   rule.Attribute,
			Requests:    constraintRequests,
			Enforcement: enforcement,
		})
		coupling = CouplingTight
	}

	return config, coupling
}

// deviceClassName generates a deterministic DeviceClass name.
func (m *DeviceClassManager) deviceClassName(profile string, partType PartitionType) string {
	// Sanitize profile for DNS label compatibility
	sanitized := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		if r >= 'A' && r <= 'Z' {
			return r + ('a' - 'A')
		}
		return '-'
	}, profile)

	// Trim leading/trailing dashes and collapse consecutive dashes
	for strings.Contains(sanitized, "--") {
		sanitized = strings.ReplaceAll(sanitized, "--", "-")
	}
	sanitized = strings.Trim(sanitized, "-")

	if sanitized == "" {
		sanitized = "default"
	}

	// Truncate profile to fit within DNS label limits (63 chars max)
	// Keep partition type suffix intact for uniqueness
	suffix := "-" + string(partType)
	maxProfileLen := 63 - len(suffix)
	if len(sanitized) > maxProfileLen {
		h := sha256.Sum256([]byte(sanitized))
		hash := hex.EncodeToString(h[:4])
		sanitized = sanitized[:maxProfileLen-9] + "-" + hash
	}

	return sanitized + suffix
}

// truncateLabel truncates a string to fit K8s label value limits (63 chars max).
// If truncation is needed, appends a short hash to preserve uniqueness.
func truncateLabel(s string) string {
	if len(s) <= 63 {
		return s
	}
	h := sha256.Sum256([]byte(s))
	hash := hex.EncodeToString(h[:4]) // 8 hex chars
	return s[:54] + "-" + hash
}

// numaKeySuffix returns a DNS-safe suffix encoding the NUMA node IDs.
// e.g., [0] → "-numa0", [0, 1] → "-numa0-1"
func numaKeySuffix(numaNodes []int64) string {
	if len(numaNodes) == 0 {
		return ""
	}
	s := fmt.Sprintf("-numa%d", numaNodes[0])
	for _, n := range numaNodes[1:] {
		s += fmt.Sprintf("-%d", n)
	}
	return s
}

// isPartitionConstraintSatisfiable checks whether a partition's devices can
// satisfy a matchAttribute constraint. It groups the partition's devices by
// the attribute value and checks if any group meets all driver count requirements.
// This is a local check on the partition's Devices slice, not a cluster-wide check.
func isPartitionConstraintSatisfiable(devices []TopologyDevice, attribute string, driverCounts map[string]int) bool {
	groups := make(map[string]map[string]int) // attrValue → baseDriverName → count

	// Track which drivers actually publish this attribute
	driversWithAttribute := make(map[string]bool)

	for _, dev := range devices {
		vals := deviceAttributeValues(dev, attribute)
		if len(vals) == 0 {
			continue // Device doesn't publish this attribute
		}
		driver := baseDriverName(dev.DriverName)
		driversWithAttribute[driver] = true
		for _, val := range vals {
			if groups[val] == nil {
				groups[val] = make(map[string]int)
			}
			groups[val][driver]++
		}
	}

	// Need at least 2 drivers with the attribute for a meaningful constraint
	if len(driversWithAttribute) < 2 {
		return false
	}

	for _, driverMap := range groups {
		satisfied := true
		for driver, needed := range driverCounts {
			base := baseDriverName(driver)
			// Only check drivers that actually publish this attribute.
			// CPU/memory don't publish pcieRoot — skip them.
			if !driversWithAttribute[base] {
				continue
			}
			if driverMap[base] < needed {
				satisfied = false
				break
			}
		}
		if satisfied {
			return true
		}
	}
	return false
}

// SyncGroupingDeviceClasses creates or updates DeviceClass objects for each
// satisfiable grouping instance discovered across all nodes.
func (m *DeviceClassManager) SyncGroupingDeviceClasses(ctx context.Context, results []GroupingResult) error {
	type groupingKey struct {
		groupingName string
		alignment    string
		numaKey      string
	}

	type groupingEntry struct {
		representative GroupingInstance
		config         PartitionConfig
		count          int
	}

	seen := make(map[string]*groupingEntry)
	for _, result := range results {
		for _, inst := range result.Instances {
			config := m.buildGroupingConfig(inst)

			nk := numaKey(inst.NUMANodes)
			key := truncateLabel(inst.GroupingName) + "-" + sanitizeForName(inst.Alignment)
			if nk != "" {
				key += "-numa" + nk
			}

			if entry, ok := seen[key]; ok {
				entry.count++
			} else {
				seen[key] = &groupingEntry{
					representative: inst,
					config:         config,
					count:          1,
				}
			}
		}
	}

	// Emit per-instance DeviceClasses (NUMA-specific)
	for key, entry := range seen {
		dc := m.buildGroupingDeviceClass(key, entry.representative, entry.config, entry.count)
		if err := m.publishDeviceClass(ctx, dc); err != nil {
			return fmt.Errorf("failed to publish DeviceClass %s: %w", dc.Name, err)
		}
	}

	// Emit aggregate DeviceClasses (one per grouping name, no NUMA selector).
	// Lets users request "any gpu-nic-pair" without specifying a NUMA node;
	// the scheduler finds a satisfiable placement automatically.
	aggregates := make(map[string]*groupingEntry)
	for _, entry := range seen {
		name := entry.representative.GroupingName
		if _, ok := aggregates[name]; !ok {
			aggConfig := m.buildGroupingAggregateConfig(entry.representative)
			aggregates[name] = &groupingEntry{
				representative: entry.representative,
				config:         aggConfig,
				count:          entry.count,
			}
		} else {
			aggregates[name].count += entry.count
		}
	}
	for _, entry := range aggregates {
		aggKey := truncateLabel(entry.representative.GroupingName) + "-" + sanitizeForName(entry.representative.Alignment)
		dc := m.buildGroupingDeviceClass(aggKey, entry.representative, entry.config, entry.count)
		dc.Name = sanitizeForName(entry.representative.GroupingName)
		delete(dc.Labels, CoordinatorDriverName+"/numa")
		if err := m.publishDeviceClass(ctx, dc); err != nil {
			return fmt.Errorf("failed to publish aggregate DeviceClass %s: %w", dc.Name, err)
		}
	}

	activeKeys := make(map[string]bool, len(seen))
	for key := range seen {
		activeKeys[key] = true
	}
	for _, entry := range aggregates {
		aggKey := truncateLabel(entry.representative.GroupingName) + "-" + sanitizeForName(entry.representative.Alignment)
		activeKeys[aggKey] = true
	}
	if err := m.cleanupStaleGroupingDeviceClasses(ctx, activeKeys); err != nil {
		klog.Errorf("Failed to cleanup stale grouping DeviceClasses: %v", err)
	}

	klog.Infof("Synced %d grouping DeviceClasses", len(seen))
	return nil
}

// buildGroupingConfig builds the opaque PartitionConfig from a grouping instance.
func (m *DeviceClassManager) buildGroupingConfig(inst GroupingInstance) PartitionConfig {
	return m.buildGroupingConfigInternal(inst, true)
}

// buildGroupingAggregateConfig builds a PartitionConfig without NUMA selectors,
// so the scheduler can place on any NUMA node with available devices.
func (m *DeviceClassManager) buildGroupingAggregateConfig(inst GroupingInstance) PartitionConfig {
	return m.buildGroupingConfigInternal(inst, false)
}

func (m *DeviceClassManager) buildGroupingConfigInternal(inst GroupingInstance, includeNUMA bool) PartitionConfig {
	config := PartitionConfig{
		Kind: "PartitionConfig",
	}

	for driverClass, count := range inst.DeviceCounts {
		sr := SubResourceConfig{
			DeviceClass: driverClass,
			Count:       count,
		}

		if cap, ok := inst.DeviceCapacity[driverClass]; ok {
			sr.Capacity = cap
		}

		if includeNUMA && len(inst.NUMANodes) > 0 {
			driver := m.driverForClass(driverClass)
			if attr, ok := m.rules.GetNUMAAttributeForDriver(driver); ok {
				if !strings.Contains(attr, "/") {
					attr = driver + "/" + attr
				}
				cel := BuildNUMACELSelector(attr, inst.NUMANodes)
				if cel != "" {
					sr.Selectors = append(sr.Selectors, cel)
				}
			} else {
				cel := BuildNUMACELSelector(AttrNUMANode, inst.NUMANodes)
				if cel != "" {
					sr.Selectors = append(sr.Selectors, cel)
				}
			}
		}

		config.SubResources = append(config.SubResources, sr)
	}

	matchRules := m.rules.GetMatchConstraintRules()
	for _, rule := range matchRules {
		if rule.Driver != "" {
			if _, ok := inst.DeviceCounts[m.rules.GetDeviceClassForDriver(rule.Driver)]; !ok {
				continue
			}
		}

		var constraintRequests []string
		if len(inst.Devices) > 0 {
			driversWithAttribute := make(map[string]bool)
			for _, dev := range inst.Devices {
				val := deviceAttributeValueString(dev, rule.Attribute)
				if val != "" {
					driversWithAttribute[baseDriverName(dev.DriverName)] = true
				}
			}
			for driver := range inst.DeviceCounts {
				rawDriver := m.driverForClass(driver)
				if driversWithAttribute[baseDriverName(rawDriver)] {
					constraintRequests = append(constraintRequests, driver)
				}
			}
		}

		if len(constraintRequests) < 2 {
			continue
		}

		enforcement := rule.Enforcement
		if enforcement == "" {
			enforcement = EnforcementRequired
		}

		config.Alignments = append(config.Alignments, AlignmentConfig{
			Attribute:   rule.Attribute,
			Requests:    constraintRequests,
			Enforcement: enforcement,
		})
	}

	return config
}

// buildGroupingDeviceClass constructs a DeviceClass for a grouping instance.
func (m *DeviceClassManager) buildGroupingDeviceClass(
	key string,
	representative GroupingInstance,
	config PartitionConfig,
	count int,
) *resourcev1.DeviceClass {
	name := sanitizeDNSLabel(key)

	celExpr := fmt.Sprintf(
		`device.driver == %q && device.attributes[%q].grouping == %q`,
		m.driverName, m.driverName, representative.GroupingName,
	)

	configJSON, err := json.Marshal(config)
	if err != nil {
		klog.Errorf("Failed to marshal grouping config: %v", err)
		configJSON = []byte("{}")
	}

	labels := map[string]string{
		CoordinatorDriverName + "/managed":   "true",
		CoordinatorDriverName + "/grouping":  truncateLabel(representative.GroupingName),
		CoordinatorDriverName + "/alignment": representative.Alignment,
	}
	if len(representative.NUMANodes) > 0 {
		labels[CoordinatorDriverName+"/numa"] = numaKey(representative.NUMANodes)
	}
	if count > 1 {
		labels[CoordinatorDriverName+"/count"] = fmt.Sprintf("%d", count)
	}

	return &resourcev1.DeviceClass{
		ObjectMeta: metav1.ObjectMeta{
			Name:   name,
			Labels: labels,
		},
		Spec: resourcev1.DeviceClassSpec{
			Selectors: []resourcev1.DeviceSelector{
				{
					CEL: &resourcev1.CELDeviceSelector{
						Expression: celExpr,
					},
				},
			},
			Config: []resourcev1.DeviceClassConfiguration{
				{
					DeviceConfiguration: resourcev1.DeviceConfiguration{
						Opaque: &resourcev1.OpaqueDeviceConfiguration{
							Driver:     m.driverName,
							Parameters: runtime.RawExtension{Raw: configJSON},
						},
					},
				},
			},
		},
	}
}

// cleanupStaleGroupingDeviceClasses removes grouping DeviceClasses that no longer match.
func (m *DeviceClassManager) cleanupStaleGroupingDeviceClasses(ctx context.Context, active map[string]bool) error {
	labelSelector := fmt.Sprintf("%s/managed=true,%s/grouping", CoordinatorDriverName, CoordinatorDriverName)
	classes, err := m.client.ResourceV1().DeviceClasses().List(ctx, metav1.ListOptions{
		LabelSelector: labelSelector,
	})
	if err != nil {
		return fmt.Errorf("failed to list grouping DeviceClasses: %w", err)
	}

	for _, dc := range classes.Items {
		grouping := dc.Labels[CoordinatorDriverName+"/grouping"]
		alignment := dc.Labels[CoordinatorDriverName+"/alignment"]
		numa := dc.Labels[CoordinatorDriverName+"/numa"]

		key := grouping + "-" + sanitizeForName(alignment)
		if numa != "" {
			key += "-numa" + numa
		}

		if _, exists := active[key]; !exists {
			if err := m.client.ResourceV1().DeviceClasses().Delete(ctx, dc.Name, metav1.DeleteOptions{}); err != nil {
				if !errors.IsNotFound(err) {
					klog.Errorf("Failed to delete stale grouping DeviceClass %s: %v", dc.Name, err)
				}
			} else {
				klog.Infof("Deleted stale grouping DeviceClass %s", dc.Name)
			}
		}
	}
	return nil
}

// driverForClass returns the raw driver name for a DeviceClass name.
// If a topology rule overrides the class name, this reverse-maps it.
func (m *DeviceClassManager) driverForClass(className string) string {
	for _, rule := range m.rules.GetRules() {
		if rule.DeviceClass == className {
			return rule.Driver
		}
	}
	return className
}

// sanitizeDNSLabel converts a string to a valid DNS label (max 63 chars).
func sanitizeDNSLabel(s string) string {
	sanitized := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		if r >= 'A' && r <= 'Z' {
			return r + ('a' - 'A')
		}
		return '-'
	}, s)

	for strings.Contains(sanitized, "--") {
		sanitized = strings.ReplaceAll(sanitized, "--", "-")
	}
	sanitized = strings.Trim(sanitized, "-")

	if sanitized == "" {
		sanitized = "default"
	}

	if len(sanitized) > 63 {
		h := sha256.Sum256([]byte(sanitized))
		hash := hex.EncodeToString(h[:4])
		sanitized = sanitized[:54] + "-" + hash
	}

	return sanitized
}

// partitionModeAttributeSuffixes lists attribute name suffixes that indicate
// a device's partition mode (e.g., "partitionMode", "computePartition").
var partitionModeAttributeSuffixes = []string{
	"partitionMode",
	"computePartition",
	"mode",
}

// detectPartitionModeAttr returns the attribute name and mode value from a
// device's extended attributes. Returns ("", "") if no partition mode found.
func detectPartitionModeAttr(dev TopologyDevice) (attrName string, mode string) {
	for name, val := range dev.ExtendedAttributes {
		for _, suffix := range partitionModeAttributeSuffixes {
			if strings.HasSuffix(name, "/"+suffix) || name == suffix {
				if val.StringValue != nil {
					return name, *val.StringValue
				}
			}
		}
	}
	return "", ""
}

// publishDeviceClass creates or updates a DeviceClass.
func (m *DeviceClassManager) publishDeviceClass(ctx context.Context, dc *resourcev1.DeviceClass) error {
	existing, err := m.client.ResourceV1().DeviceClasses().Get(ctx, dc.Name, metav1.GetOptions{})
	if errors.IsNotFound(err) {
		_, err = m.client.ResourceV1().DeviceClasses().Create(ctx, dc, metav1.CreateOptions{})
		if err != nil {
			return fmt.Errorf("failed to create DeviceClass %s: %w", dc.Name, err)
		}
		klog.Infof("Created DeviceClass %s", dc.Name)
		return nil
	}
	if err != nil {
		return fmt.Errorf("failed to get DeviceClass %s: %w", dc.Name, err)
	}

	// Update existing
	dc.ResourceVersion = existing.ResourceVersion
	_, err = m.client.ResourceV1().DeviceClasses().Update(ctx, dc, metav1.UpdateOptions{})
	if err != nil {
		return fmt.Errorf("failed to update DeviceClass %s: %w", dc.Name, err)
	}
	klog.Infof("Updated DeviceClass %s", dc.Name)
	return nil
}
